<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SharedKernel\TestTask.Timescale.SharedKernel.Domain\TestTask.Timescale.SharedKernel.Domain.csproj" />
  </ItemGroup>

</Project>
