// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.Timescale.Infrastructure;

#nullable disable

namespace TestTask.Timescale.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Timescale.Domain.Aggregates.MetricsAggregate.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgExecutionDuration")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_execution_duration");

                    b.Property<double>("AvgValue")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_value");

                    b.Property<double>("DeltaDate")
                        .HasColumnType("double precision")
                        .HasColumnName("delta_date");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision")
                        .HasColumnName("median_value");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("min_date");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<int>("TimeScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("time_scale_id");

                    b.HasKey("Id")
                        .HasName("pk_result");

                    b.HasIndex("TimeScaleId")
                        .IsUnique()
                        .HasDatabaseName("ix_result_time_scale_id");

                    b.ToTable("result", (string)null);
                });

            modelBuilder.Entity("TestTask.Timescale.Domain.Aggregates.RecordAggregate.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("TimeScaleId")
                        .HasColumnType("integer")
                        .HasColumnName("time_scale_id");

                    b.HasKey("Id")
                        .HasName("pk_values");

                    b.HasIndex("TimeScaleId")
                        .HasDatabaseName("ix_values_time_scale_id");

                    b.ToTable("values", (string)null);
                });

            modelBuilder.Entity("TestTask.Timescale.Domain.Aggregates.TimeScaleAggregate.TimeScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.HasKey("Id")
                        .HasName("pk_time_scales");

                    b.ToTable("time_scales", (string)null);
                });

            modelBuilder.Entity("TestTask.Timescale.Domain.Aggregates.MetricsAggregate.Metrics", b =>
                {
                    b.HasOne("TestTask.Timescale.Domain.Aggregates.TimeScaleAggregate.TimeScale", null)
                        .WithOne()
                        .HasForeignKey("TestTask.Timescale.Domain.Aggregates.MetricsAggregate.Metrics", "TimeScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_result_time_scales_time_scale_id");
                });

            modelBuilder.Entity("TestTask.Timescale.Domain.Aggregates.RecordAggregate.Record", b =>
                {
                    b.HasOne("TestTask.Timescale.Domain.Aggregates.TimeScaleAggregate.TimeScale", null)
                        .WithMany()
                        .HasForeignKey("TimeScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_values_time_scales_time_scale_id");

                    b.OwnsOne("TestTask.Timescale.Domain.Aggregates.RecordAggregate.ExecutionDuration", "Time", b1 =>
                        {
                            b1.Property<int>("RecordId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double>("Seconds")
                                .HasColumnType("double precision")
                                .HasColumnName("execution_time");

                            b1.HasKey("RecordId");

                            b1.ToTable("values");

                            b1.WithOwner()
                                .HasForeignKey("RecordId")
                                .HasConstraintName("fk_values_values_id");
                        });

                    b.OwnsOne("TestTask.Timescale.Domain.Aggregates.RecordAggregate.RecordValue", "Value", b1 =>
                        {
                            b1.Property<int>("RecordId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double>("Indicator")
                                .HasColumnType("double precision")
                                .HasColumnName("value");

                            b1.HasKey("RecordId");

                            b1.ToTable("values");

                            b1.WithOwner()
                                .HasForeignKey("RecordId")
                                .HasConstraintName("fk_values_values_id");
                        });

                    b.OwnsOne("TestTask.Timescale.Domain.Aggregates.RecordAggregate.Timestamp", "Date", b1 =>
                        {
                            b1.Property<int>("RecordId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date");

                            b1.HasKey("RecordId");

                            b1.ToTable("values");

                            b1.WithOwner()
                                .HasForeignKey("RecordId")
                                .HasConstraintName("fk_values_values_id");
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Time")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
