<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestTask.Timescale.SharedKernel.Domain\TestTask.Timescale.SharedKernel.Domain.csproj" />
  </ItemGroup>

</Project>
